package de.dasbabypixel.gamelauncher.gles

import de.dasbabypixel.gamelauncher.gles.es32.*

interface GLES32 :
    GLES31,
    glPopDebugGroup,
    glObjectLabel,
    glDebugMessageControl,
    glDrawElementsInstancedBaseVertex,
    glDrawElementsBaseVertex,
    glColorMaski,
    glBlendBarrier,
    glGetSamplerParameterIiv,
    glGetSamplerParameterIuiv,
    glMinSampleShading,
    glDebugMessageInsert,
    glBlendFuncSeparatei,
    glIsEnabledi,
    glBlendFunci,
    glDebugMessageCallback,
    glPushDebugGroup,
    glGetObjectPtrLabel,
    glEnablei,
    glDisablei,
    glGetGraphicsResetStatus,
    glTexStorage3DMultisample,
    glCopyImageSubData,
    glPatchParameteri,
    glTexBufferRange,
    glGetnUniformfv,
    glGetnUniformiv,
    glGetnUniformuiv,
    glBlendEquationSeparatei,
    glGetPointerv,
    glSamplerParameterIiv,
    glSamplerParameterIuiv,
    glObjectPtrLabel,
    glTexBuffer,
    glDrawRangeElementsBaseVertex,
    glFramebufferTexture,
    glGetTexParameterIiv,
    glGetTexParameterIuiv,
    glGetDebugMessageLog,
    glGetObjectLabel,
    glPrimitiveBoundingBox,
    glReadnPixels,
    glBlendEquationi,
    glTexParameterIiv,
    glTexParameterIuiv