package de.dasbabypixel.gamelauncher.gles.es20

interface glAttachShader {
    /**
    * Name
    * ----
    * 
    * glAttachShader — Attaches a shader object to a program object
    * 
    * C Specification
    * ---------------
    * 
    * | `void **glAttachShader**(` | GLuint program, |
    * | --- | --- |
    * |   | GLuint shader`)`; |
    * 
    * Parameters
    * ----------
    * 
    * _`program`_
    * 
    * Specifies the program object to which a shader object will be attached.
    * 
    * _`shader`_
    * 
    * Specifies the shader object that is to be attached.
    * 
    * Description
    * -----------
    * 
    * In order to create a complete shader program, there must be a way to specify the list of things that will be linked together. Program objects provide this mechanism. Shaders that are to be linked together in a program object must first be attached to that program object. `glAttachShader` attaches the shader object specified by _`shader`_ to the program object specified by _`program`_. This indicates that _`shader`_ will be included in link operations that will be performed on _`program`_.
    * 
    * All operations that can be performed on a shader object are valid whether or not the shader object is attached to a program object. It is permissible to attach a shader object to a program object before source code has been loaded into the shader object or before the shader object has been compiled. It is not permissible to attach multiple shader objects of the same type. It is permissible to attach a shader object to more than one program object. If a shader object is deleted while it is attached to a program object, it will be flagged for deletion, and deletion will not occur until [glDetachShader][de.dasbabypixel.gamelauncher.gles.es20.glDetachShader.glDetachShader] is called to detach it from all program objects to which it is attached.
    * 
    * Errors
    * ------
    * 
    * `GL_INVALID_VALUE` is generated if either _`program`_ or _`shader`_ is not a value generated by OpenGL.
    * 
    * `GL_INVALID_OPERATION` is generated if _`program`_ is not a program object.
    * 
    * `GL_INVALID_OPERATION` is generated if _`shader`_ is not a shader object.
    * 
    * `GL_INVALID_OPERATION` is generated if _`shader`_ is already attached to _`program`_.
    * 
    * `GL_INVALID_OPERATION` is generated if a shader of the same type as _`shader`_ is already attached to _`program`_.
    * 
    * Associated Gets
    * ---------------
    * 
    * [glGetAttachedShaders][de.dasbabypixel.gamelauncher.gles.es20.glGetAttachedShaders.glGetAttachedShaders] with the handle of a valid program object
    * 
    * [glGetShaderInfoLog][de.dasbabypixel.gamelauncher.gles.es20.glGetShaderInfoLog.glGetShaderInfoLog]
    * 
    * [glGetShaderSource][de.dasbabypixel.gamelauncher.gles.es20.glGetShaderSource.glGetShaderSource]
    * 
    * [glIsProgram][de.dasbabypixel.gamelauncher.gles.es20.glIsProgram.glIsProgram]
    * 
    * [glIsShader][de.dasbabypixel.gamelauncher.gles.es20.glIsShader.glIsShader]
    * 
    * API Version Support
    * -------------------
    * 
    * 
    * |  | **OpenGL ES API Version** |  |  |  |
    * | --- | --- | --- | --- | --- |
    * | **Function Name** | **2.0** | **3.0** | **3.1** | **3.2** |
    * | glAttachShader | ✔ | ✔ | ✔ | ✔ |
    * 
    * See Also
    * --------
    * 
    * [glCompileShader][de.dasbabypixel.gamelauncher.gles.es20.glCompileShader.glCompileShader], [glCreateShader][de.dasbabypixel.gamelauncher.gles.es20.glCreateShader.glCreateShader], [glDeleteShader][de.dasbabypixel.gamelauncher.gles.es20.glDeleteShader.glDeleteShader], [glDetachShader][de.dasbabypixel.gamelauncher.gles.es20.glDetachShader.glDetachShader], [glLinkProgram][de.dasbabypixel.gamelauncher.gles.es20.glLinkProgram.glLinkProgram], [glShaderSource][de.dasbabypixel.gamelauncher.gles.es20.glShaderSource.glShaderSource]
    * 
    * Copyright
    * ---------
    * 
    * Copyright © 2003-2005 3Dlabs Inc. Ltd. Copyright © 2010-2015 Khronos Group. This material may be distributed subject to the terms and conditions set forth in the Open Publication License, v 1.0, 8 June 1999. [https://opencontent.org/openpub/](https://opencontent.org/openpub/).
    * 
    * @see de.dasbabypixel.gamelauncher.gles.es20.glAttachShader.glAttachShader
    */
    fun glAttachShader(program: UInt, shader: UInt)
}