package de.dasbabypixel.gamelauncher.gles.es20

interface glBlendEquationSeparate {
    /**
    * Name
    * ----
    * 
    * glBlendEquationSeparate — set the RGB blend equation and the alpha blend equation separately
    * 
    * C Specification
    * ---------------
    * 
    * | `void **glBlendEquationSeparate**(` | GLenum modeRGB, |
    * | --- | --- |
    * |   | GLenum modeAlpha`)`; |
    * 
    * | `void **glBlendEquationSeparatei**(` | GLuint buf, |
    * | --- | --- |
    * |   | GLenum modeRGB, |
    * |   | GLenum modeAlpha`)`; |
    * 
    * Parameters
    * ----------
    * 
    * _`buf`_
    * 
    * for `glBlendEquationSeparatei`, specifies the index of the draw buffer for which to set the blend equations.
    * 
    * _`modeRGB`_
    * 
    * specifies the RGB blend equation, how the red, green, and blue components of the source and destination colors are combined. It must be `GL_FUNC_ADD`, `GL_FUNC_SUBTRACT`, `GL_FUNC_REVERSE_SUBTRACT`, `GL_MIN`, `GL_MAX`.
    * 
    * _`modeAlpha`_
    * 
    * specifies the alpha blend equation, how the alpha component of the source and destination colors are combined. It must be `GL_FUNC_ADD`, `GL_FUNC_SUBTRACT`, `GL_FUNC_REVERSE_SUBTRACT`, `GL_MIN`, `GL_MAX`.
    * 
    * Description
    * -----------
    * 
    * The blend equations determines how a new pixel (the ''source'' color) is combined with a pixel already in the framebuffer (the ''destination'' color). This function specifies one blend equation for the RGB-color components and one blend equation for the alpha component. `glBlendEquationSeparatei` specifies the blend equations for a single draw buffer whereas `glBlendEquationSeparate` sets the blend equations for all draw buffers.
    * 
    * The blend equations use the source and destination blend factors specified by either [glBlendFunc][de.dasbabypixel.gamelauncher.gles.es20.glBlendFunc.glBlendFunc] or [glBlendFuncSeparate][de.dasbabypixel.gamelauncher.gles.es20.glBlendFuncSeparate.glBlendFuncSeparate]. See [glBlendFunc][de.dasbabypixel.gamelauncher.gles.es20.glBlendFunc.glBlendFunc] or [glBlendFuncSeparate][de.dasbabypixel.gamelauncher.gles.es20.glBlendFuncSeparate.glBlendFuncSeparate] for a description of the various blend factors.
    * 
    * In the equations that follow, source and destination color components are referred to as R s G s B s A s and R d G d B d A d , respectively. The result color is referred to as R r G r B r A r . The source and destination blend factors are denoted s R s G s B s A and d R d G d B d A , respectively. For these equations all color components are understood to have values in the range 0 1 .
    * 
    * 
    * | **Mode** | **RGB Components** | **Alpha Component** |
    * | --- | --- | --- |
    * | `GL_FUNC_ADD` | Rr \= R s ⁢ s R + R d ⁢ d R Gr \= G s ⁢ s G + G d ⁢ d G Br \= B s ⁢ s B + B d ⁢ d B | Ar \= A s ⁢ s A + A d ⁢ d A |
    * | `GL_FUNC_SUBTRACT` | Rr \= R s ⁢ s R \- R d ⁢ d R Gr \= G s ⁢ s G \- G d ⁢ d G Br \= B s ⁢ s B \- B d ⁢ d B | Ar \= A s ⁢ s A \- A d ⁢ d A |
    * | `GL_FUNC_REVERSE_SUBTRACT` | Rr \= R d ⁢ d R \- R s ⁢ s R Gr \= G d ⁢ d G \- G s ⁢ s G Br \= B d ⁢ d B \- B s ⁢ s B | Ar \= A d ⁢ d A \- A s ⁢ s A |
    * | `GL_MIN` | Rr \= min ⁡ R s R d Gr \= min ⁡ G s G d Br \= min ⁡ B s B d | Ar \= min ⁡ A s A d |
    * | `GL_MAX` | Rr \= max ⁡ R s R d Gr \= max ⁡ G s G d Br \= max ⁡ B s B d | Ar \= max ⁡ A s A d |
    * 
    * The results of these equations are clamped to the range 0 1 .
    * 
    * The `GL_MIN` and `GL_MAX` equations are useful for applications that analyze image data (image thresholding against a constant color, for example). The `GL_FUNC_ADD` equation is useful for antialiasing and transparency, among other things.
    * 
    * Initially, both the RGB blend equation and the alpha blend equation are set to `GL_FUNC_ADD`.
    * 
    * Notes
    * -----
    * 
    * The `GL_MIN`, and `GL_MAX` equations do not use the source or destination factors, only the source and destination colors.
    * 
    * Errors
    * ------
    * 
    * `GL_INVALID_ENUM` is generated if either _`modeRGB`_ or _`modeAlpha`_ is not one of `GL_FUNC_ADD`, `GL_FUNC_SUBTRACT`, `GL_FUNC_REVERSE_SUBTRACT`, `GL_MAX`, or `GL_MIN`.
    * 
    * `GL_INVALID_VALUE` is generated by `glBlendEquationSeparatei` if _`buf`_ is greater than or equal to the value of `GL_MAX_DRAW_BUFFERS`.
    * 
    * Associated Gets
    * ---------------
    * 
    * [glGet][de.dasbabypixel.gamelauncher.gles.es20.glGetBooleanv.glGetBooleanv] with an argument of `GL_BLEND_EQUATION_RGB`
    * 
    * [glGet][de.dasbabypixel.gamelauncher.gles.es20.glGetBooleanv.glGetBooleanv] with an argument of `GL_BLEND_EQUATION_ALPHA`
    * 
    * API Version Support
    * -------------------
    * 
    * 
    * |  | **OpenGL ES API Version** |  |  |  |
    * | --- | --- | --- | --- | --- |
    * | **Function Name** | **2.0** | **3.0** | **3.1** | **3.2** |
    * | glBlendEquationSeparate | ✔ | ✔ | ✔ | ✔ |
    * | glBlendEquationSeparatei | \- | \- | \- | ✔ |
    * 
    * See Also
    * --------
    * 
    * [glGetString][de.dasbabypixel.gamelauncher.gles.es20.glGetString.glGetString], [glBlendColor][de.dasbabypixel.gamelauncher.gles.es20.glBlendColor.glBlendColor], [glBlendEquation][de.dasbabypixel.gamelauncher.gles.es20.glBlendEquation.glBlendEquation], [glBlendFunc][de.dasbabypixel.gamelauncher.gles.es20.glBlendFunc.glBlendFunc], [glBlendFuncSeparate][de.dasbabypixel.gamelauncher.gles.es20.glBlendFuncSeparate.glBlendFuncSeparate]
    * 
    * Copyright
    * ---------
    * 
    * Copyright © 1991-2006 Silicon Graphics, Inc. Copyright © 2010-2015 Khronos Group. This document is licensed under the SGI Free Software B License. For details, see [https://khronos.org/registry/OpenGL-Refpages/LICENSES/LicenseRef-FreeB.txt](https://khronos.org/registry/OpenGL-Refpages/LICENSES/LicenseRef-FreeB.txt).
    * 
    * @see de.dasbabypixel.gamelauncher.gles.es20.glBlendEquationSeparate.glBlendEquationSeparate
    * @see de.dasbabypixel.gamelauncher.gles.es32.glBlendEquationSeparatei.glBlendEquationSeparatei
    */
    fun glBlendEquationSeparate(modeRGB: Int, modeAlpha: Int)
}