package de.dasbabypixel.gamelauncher.gles.es20

interface glCompileShader {
    /**
    * Name
    * ----
    * 
    * glCompileShader — Compiles a shader object
    * 
    * C Specification
    * ---------------
    * 
    * | `void **glCompileShader**(` | GLuint shader`)`; |
    * | --- | --- |
    * 
    * Parameters
    * ----------
    * 
    * _`shader`_
    * 
    * Specifies the shader object to be compiled.
    * 
    * Description
    * -----------
    * 
    * `glCompileShader` compiles the source code strings that have been stored in the shader object specified by _`shader`_.
    * 
    * The compilation status will be stored as part of the shader object's state. This value will be set to `GL_TRUE` if the shader was compiled without errors and is ready for use, and `GL_FALSE` otherwise. It can be queried by calling [glGetShaderiv][de.dasbabypixel.gamelauncher.gles.es20.glGetShaderiv.glGetShaderiv] with arguments _`shader`_ and `GL_COMPILE_STATUS`.
    * 
    * Compilation of a shader can fail for a number of reasons as specified by the OpenGL ES Shading Language Specification. Whether or not the compilation was successful, information about the compilation can be obtained from the shader object's information log by calling [glGetShaderInfoLog][de.dasbabypixel.gamelauncher.gles.es20.glGetShaderInfoLog.glGetShaderInfoLog].
    * 
    * Errors
    * ------
    * 
    * `GL_INVALID_VALUE` is generated if _`shader`_ is not a value generated by OpenGL.
    * 
    * `GL_INVALID_OPERATION` is generated if _`shader`_ is not a shader object.
    * 
    * Associated Gets
    * ---------------
    * 
    * [glGetShaderInfoLog][de.dasbabypixel.gamelauncher.gles.es20.glGetShaderInfoLog.glGetShaderInfoLog] with argument _`shader`_
    * 
    * [glGetShaderiv][de.dasbabypixel.gamelauncher.gles.es20.glGetShaderiv.glGetShaderiv] with arguments _`shader`_ and `GL_COMPILE_STATUS`
    * 
    * [glIsShader][de.dasbabypixel.gamelauncher.gles.es20.glIsShader.glIsShader]
    * 
    * API Version Support
    * -------------------
    * 
    * 
    * |  | **OpenGL ES API Version** |  |  |  |
    * | --- | --- | --- | --- | --- |
    * | **Function Name** | **2.0** | **3.0** | **3.1** | **3.2** |
    * | glCompileShader | ✔ | ✔ | ✔ | ✔ |
    * 
    * See Also
    * --------
    * 
    * [glCreateShader][de.dasbabypixel.gamelauncher.gles.es20.glCreateShader.glCreateShader], [glLinkProgram][de.dasbabypixel.gamelauncher.gles.es20.glLinkProgram.glLinkProgram], [glShaderSource][de.dasbabypixel.gamelauncher.gles.es20.glShaderSource.glShaderSource]
    * 
    * Copyright
    * ---------
    * 
    * Copyright © 2003-2005 3Dlabs Inc. Ltd. Copyright © 2010-2015 Khronos Group. This material may be distributed subject to the terms and conditions set forth in the Open Publication License, v 1.0, 8 June 1999. [https://opencontent.org/openpub/](https://opencontent.org/openpub/).
    * 
    * @see de.dasbabypixel.gamelauncher.gles.es20.glCompileShader.glCompileShader
    */
    fun glCompileShader(shader: UInt)
}