package de.dasbabypixel.gamelauncher.gles.es20

interface glColorMask {
    /**
    * Name
    * ----
    * 
    * glColorMask, glColorMaski — enable and disable writing of frame buffer color components
    * 
    * C Specification
    * ---------------
    * 
    * | `void **glColorMask**(` | GLboolean red, |
    * | --- | --- |
    * |   | GLboolean green, |
    * |   | GLboolean blue, |
    * |   | GLboolean alpha`)`; |
    * 
    * | `void **glColorMaski**(` | GLuint buf, |
    * | --- | --- |
    * |   | GLboolean red, |
    * |   | GLboolean green, |
    * |   | GLboolean blue, |
    * |   | GLboolean alpha`)`; |
    * 
    * Parameters
    * ----------
    * 
    * _`buf`_
    * 
    * For `glColorMaski`, specifies the index of the draw buffer whose color mask to set.
    * 
    * _`red`_, _`green`_, _`blue`_, _`alpha`_
    * 
    * Specify whether red, green, blue, and alpha are to be written into the frame buffer. The initial values are all `GL_TRUE`, indicating that the color components are written.
    * 
    * Description
    * -----------
    * 
    * `glColorMask` and `glColorMaski` specify whether the individual color components in the frame buffer can or cannot be written. `glColorMaski` sets the mask for a specific draw buffer, whereas `glColorMask` sets the mask for all draw buffers. If _`red`_ is `GL_FALSE`, for example, no change is made to the red component of any pixel in any of the color buffers, regardless of the drawing operation attempted.
    * 
    * Changes to individual bits of components cannot be controlled. Rather, changes are either enabled or disabled for entire color components.
    * 
    * Associated Gets
    * ---------------
    * 
    * [glGet][de.dasbabypixel.gamelauncher.gles.es20.glGetBooleanv.glGetBooleanv] with argument `GL_COLOR_WRITEMASK`
    * 
    * Errors
    * ------
    * 
    * `GL_INVALID_VALUE` is generated by `glColorMaski` if _`buf`_ is greater than or equal to the value of `GL_MAX_DRAW_BUFFERS`.
    * 
    * API Version Support
    * -------------------
    * 
    * 
    * |  | **OpenGL ES API Version** |  |  |  |
    * | --- | --- | --- | --- | --- |
    * | **Function Name** | **2.0** | **3.0** | **3.1** | **3.2** |
    * | glColorMask | ✔ | ✔ | ✔ | ✔ |
    * | glColorMaski | \- | \- | \- | ✔ |
    * 
    * See Also
    * --------
    * 
    * [glClear][de.dasbabypixel.gamelauncher.gles.es20.glClear.glClear], [glDepthMask][de.dasbabypixel.gamelauncher.gles.es20.glDepthMask.glDepthMask], [glStencilMask][de.dasbabypixel.gamelauncher.gles.es20.glStencilMask.glStencilMask]
    * 
    * Copyright
    * ---------
    * 
    * Copyright © 1991-2006 Silicon Graphics, Inc. Copyright © 2010-2015 Khronos Group. This document is licensed under the SGI Free Software B License. For details, see [https://khronos.org/registry/OpenGL-Refpages/LICENSES/LicenseRef-FreeB.txt](https://khronos.org/registry/OpenGL-Refpages/LICENSES/LicenseRef-FreeB.txt).
    * 
    * @see de.dasbabypixel.gamelauncher.gles.es20.glColorMask.glColorMask
    * @see de.dasbabypixel.gamelauncher.gles.es32.glColorMaski.glColorMaski
    */
    fun glColorMask(red: Boolean, green: Boolean, blue: Boolean, alpha: Boolean)
}