package de.dasbabypixel.gamelauncher.gles.es20

interface glDeleteProgram {
    /**
    * Name
    * ----
    * 
    * glDeleteProgram — Deletes a program object
    * 
    * C Specification
    * ---------------
    * 
    * | `void **glDeleteProgram**(` | GLuint program`)`; |
    * | --- | --- |
    * 
    * Parameters
    * ----------
    * 
    * _`program`_
    * 
    * Specifies the program object to be deleted.
    * 
    * Description
    * -----------
    * 
    * `glDeleteProgram` frees the memory and invalidates the name associated with the program object specified by _`program.`_ This command effectively undoes the effects of a call to [glCreateProgram][de.dasbabypixel.gamelauncher.gles.es20.glCreateProgram.glCreateProgram].
    * 
    * If a program object is in use as part of current rendering state, it will be flagged for deletion, but it will not be deleted until it is no longer part of current state for any rendering context. If a program object to be deleted has shader objects attached to it, those shader objects will be automatically detached but not deleted unless they have already been flagged for deletion by a previous call to [glDeleteShader][de.dasbabypixel.gamelauncher.gles.es20.glDeleteShader.glDeleteShader]. A value of 0 for _`program`_ will be silently ignored.
    * 
    * To determine whether a program object has been flagged for deletion, call [glGetProgramiv][de.dasbabypixel.gamelauncher.gles.es20.glGetProgramiv.glGetProgramiv] with arguments _`program`_ and `GL_DELETE_STATUS`.
    * 
    * Errors
    * ------
    * 
    * `GL_INVALID_VALUE` is generated if _`program`_ is not a value generated by OpenGL.
    * 
    * Associated Gets
    * ---------------
    * 
    * [glGet][de.dasbabypixel.gamelauncher.gles.es20.glGetBooleanv.glGetBooleanv] with argument `GL_CURRENT_PROGRAM`
    * 
    * [glGetProgramiv][de.dasbabypixel.gamelauncher.gles.es20.glGetProgramiv.glGetProgramiv] with arguments _`program`_ and `GL_DELETE_STATUS`
    * 
    * [glIsProgram][de.dasbabypixel.gamelauncher.gles.es20.glIsProgram.glIsProgram]
    * 
    * API Version Support
    * -------------------
    * 
    * 
    * |  | **OpenGL ES API Version** |  |  |  |
    * | --- | --- | --- | --- | --- |
    * | **Function Name** | **2.0** | **3.0** | **3.1** | **3.2** |
    * | glDeleteProgram | ✔ | ✔ | ✔ | ✔ |
    * 
    * See Also
    * --------
    * 
    * [glCreateShader][de.dasbabypixel.gamelauncher.gles.es20.glCreateShader.glCreateShader], [glDetachShader][de.dasbabypixel.gamelauncher.gles.es20.glDetachShader.glDetachShader], [glUseProgram][de.dasbabypixel.gamelauncher.gles.es20.glUseProgram.glUseProgram]
    * 
    * Copyright
    * ---------
    * 
    * Copyright © 2003-2005 3Dlabs Inc. Ltd. Copyright © 2010-2015 Khronos Group. This material may be distributed subject to the terms and conditions set forth in the Open Publication License, v 1.0, 8 June 1999. [https://opencontent.org/openpub/](https://opencontent.org/openpub/).
    * 
    * @see de.dasbabypixel.gamelauncher.gles.es20.glDeleteProgram.glDeleteProgram
    */
    fun glDeleteProgram(program: UInt)
}