package de.dasbabypixel.gamelauncher.gles.es20

interface glDetachShader {
    /**
    * Name
    * ----
    * 
    * glDetachShader — Detaches a shader object from a program object to which it is attached
    * 
    * C Specification
    * ---------------
    * 
    * | `void **glDetachShader**(` | GLuint program, |
    * | --- | --- |
    * |   | GLuint shader`)`; |
    * 
    * Parameters
    * ----------
    * 
    * _`program`_
    * 
    * Specifies the program object from which to detach the shader object.
    * 
    * _`shader`_
    * 
    * Specifies the shader object to be detached.
    * 
    * Description
    * -----------
    * 
    * `glDetachShader` detaches the shader object specified by _`shader`_ from the program object specified by _`program`_. This command can be used to undo the effect of the command [glAttachShader][de.dasbabypixel.gamelauncher.gles.es20.glAttachShader.glAttachShader].
    * 
    * If _`shader`_ has already been flagged for deletion by a call to [glDeleteShader][de.dasbabypixel.gamelauncher.gles.es20.glDeleteShader.glDeleteShader] and it is not attached to any other program object, it will be deleted after it has been detached.
    * 
    * Errors
    * ------
    * 
    * `GL_INVALID_VALUE` is generated if either _`program`_ or _`shader`_ is a value that was not generated by OpenGL.
    * 
    * `GL_INVALID_OPERATION` is generated if _`program`_ is not a program object.
    * 
    * `GL_INVALID_OPERATION` is generated if _`shader`_ is not a shader object.
    * 
    * `GL_INVALID_OPERATION` is generated if _`shader`_ is not attached to _`program`_.
    * 
    * Associated Gets
    * ---------------
    * 
    * [glGetAttachedShaders][de.dasbabypixel.gamelauncher.gles.es20.glGetAttachedShaders.glGetAttachedShaders] with the handle of a valid program object
    * 
    * [glGetShaderiv][de.dasbabypixel.gamelauncher.gles.es20.glGetShaderiv.glGetShaderiv] with arguments _`shader`_ and `GL_DELETE_STATUS`
    * 
    * [glIsProgram][de.dasbabypixel.gamelauncher.gles.es20.glIsProgram.glIsProgram]
    * 
    * [glIsShader][de.dasbabypixel.gamelauncher.gles.es20.glIsShader.glIsShader]
    * 
    * API Version Support
    * -------------------
    * 
    * 
    * |  | **OpenGL ES API Version** |  |  |  |
    * | --- | --- | --- | --- | --- |
    * | **Function Name** | **2.0** | **3.0** | **3.1** | **3.2** |
    * | glDetachShader | ✔ | ✔ | ✔ | ✔ |
    * 
    * See Also
    * --------
    * 
    * [glAttachShader][de.dasbabypixel.gamelauncher.gles.es20.glAttachShader.glAttachShader]
    * 
    * Copyright
    * ---------
    * 
    * Copyright © 2003-2005 3Dlabs Inc. Ltd. Copyright © 2010-2015 Khronos Group. This material may be distributed subject to the terms and conditions set forth in the Open Publication License, v 1.0, 8 June 1999. [https://opencontent.org/openpub/](https://opencontent.org/openpub/).
    * 
    * @see de.dasbabypixel.gamelauncher.gles.es20.glDetachShader.glDetachShader
    */
    fun glDetachShader(program: UInt, shader: UInt)
}