package de.dasbabypixel.gamelauncher.gles.es20

interface glGetShaderiv {
    /**
    * Name
    * ----
    * 
    * glGetShaderiv — Returns a parameter from a shader object
    * 
    * C Specification
    * ---------------
    * 
    * | `void **glGetShaderiv**(` | GLuint shader, |
    * | --- | --- |
    * |   | GLenum pname, |
    * |   | GLint \*params`)`; |
    * 
    * Parameters
    * ----------
    * 
    * _`shader`_
    * 
    * Specifies the shader object to be queried.
    * 
    * _`pname`_
    * 
    * Specifies the object parameter. Accepted symbolic names are `GL_SHADER_TYPE`, `GL_DELETE_STATUS`, `GL_COMPILE_STATUS`, `GL_INFO_LOG_LENGTH`, `GL_SHADER_SOURCE_LENGTH`.
    * 
    * _`params`_
    * 
    * Returns the requested object parameter.
    * 
    * Description
    * -----------
    * 
    * `glGetShaderiv` returns in _`params`_ the value of a parameter for a specific shader object. The following parameters are defined:
    * 
    * `GL_SHADER_TYPE`
    * 
    * _`params`_ returns `GL_VERTEX_SHADER` if _`shader`_ is a vertex shader object, `GL_TESS_CONTROL_SHADER` if _`shader`_ is a tesselation control shader object,`GL_TESS_EVALUATION_SHADER` if _`shader`_ is a tesselation evaluation shader object,`GL_GEOMETRY_SHADER` if _`shader`_ is a geometry shader object, `GL_FRAGMENT_SHADER` if _`shader`_ is a fragment shader, and `GL_COMPUTE_SHADER` if _`shader`_ is a compute shader object.
    * 
    * `GL_DELETE_STATUS`
    * 
    * _`params`_ returns `GL_TRUE` if _`shader`_ is currently flagged for deletion, and `GL_FALSE` otherwise.
    * 
    * `GL_COMPILE_STATUS`
    * 
    * _`params`_ returns `GL_TRUE` if the last compile operation on _`shader`_ was successful, and `GL_FALSE` otherwise.
    * 
    * `GL_INFO_LOG_LENGTH`
    * 
    * _`params`_ returns the number of characters in the information log for _`shader`_ including the null termination character (i.e., the size of the character buffer required to store the information log). If _`shader`_ has no information log, a value of 0 is returned.
    * 
    * `GL_SHADER_SOURCE_LENGTH`
    * 
    * _`params`_ returns the length of the concatenation of the source strings that make up the shader source for the _`shader`_, including the null termination character. (i.e., the size of the character buffer required to store the shader source). If no source code exists, 0 is returned.
    * 
    * Notes
    * -----
    * 
    * If an error is generated, no change is made to the contents of _`params`_.
    * 
    * Errors
    * ------
    * 
    * `GL_INVALID_VALUE` is generated if _`shader`_ is not a value generated by OpenGL.
    * 
    * `GL_INVALID_OPERATION` is generated if _`shader`_ does not refer to a shader object.
    * 
    * `GL_INVALID_ENUM` is generated if _`pname`_ is not an accepted value.
    * 
    * Associated Gets
    * ---------------
    * 
    * [glGetShaderInfoLog][de.dasbabypixel.gamelauncher.gles.es20.glGetShaderInfoLog.glGetShaderInfoLog] with argument _`shader`_
    * 
    * [glGetShaderSource][de.dasbabypixel.gamelauncher.gles.es20.glGetShaderSource.glGetShaderSource] with argument _`shader`_
    * 
    * [glIsShader][de.dasbabypixel.gamelauncher.gles.es20.glIsShader.glIsShader]
    * 
    * API Version Support
    * -------------------
    * 
    * 
    * |  | **OpenGL ES API Version** |  |  |  |
    * | --- | --- | --- | --- | --- |
    * | **Function Name** | **2.0** | **3.0** | **3.1** | **3.2** |
    * | glGetShaderiv | ✔ | ✔ | ✔ | ✔ |
    * 
    * See Also
    * --------
    * 
    * [glCompileShader][de.dasbabypixel.gamelauncher.gles.es20.glCompileShader.glCompileShader], [glCreateShader][de.dasbabypixel.gamelauncher.gles.es20.glCreateShader.glCreateShader], [glDeleteShader][de.dasbabypixel.gamelauncher.gles.es20.glDeleteShader.glDeleteShader], [glGetProgramiv][de.dasbabypixel.gamelauncher.gles.es20.glGetProgramiv.glGetProgramiv], [glShaderSource][de.dasbabypixel.gamelauncher.gles.es20.glShaderSource.glShaderSource]
    * 
    * Copyright
    * ---------
    * 
    * Copyright © 2003-2005 3Dlabs Inc. Ltd. Copyright © 2010-2015 Khronos Group. This material may be distributed subject to the terms and conditions set forth in the Open Publication License, v 1.0, 8 June 1999. [https://opencontent.org/openpub/](https://opencontent.org/openpub/).
    * 
    * @see de.dasbabypixel.gamelauncher.gles.es20.glGetShaderiv.glGetShaderiv
    */
    fun glGetShaderiv(shader: UInt, pname: Int, params: de.dasbabypixel.gamelauncher.buffers.IntBuffer)
}