package de.dasbabypixel.gamelauncher.gles.es20

interface glGetAttribLocation {
    /**
    * Name
    * ----
    * 
    * glGetAttribLocation — Returns the location of an attribute variable
    * 
    * C Specification
    * ---------------
    * 
    * | `GLint **glGetAttribLocation**(` | GLuint program, |
    * | --- | --- |
    * |   | const GLchar \*name`)`; |
    * 
    * Parameters
    * ----------
    * 
    * _`program`_
    * 
    * Specifies the program object to be queried.
    * 
    * _`name`_
    * 
    * Points to a null terminated string containing the name of the attribute variable whose location is to be queried.
    * 
    * Description
    * -----------
    * 
    * `glGetAttribLocation` queries the previously linked program object specified by _`program`_ for the attribute variable specified by _`name`_ and returns the index of the generic vertex attribute that is bound to that attribute variable. If _`name`_ is a matrix attribute variable, the index of the first column of the matrix is returned. If the named attribute variable is not an active attribute in the specified program object or if _`name`_ starts with the reserved prefix "gl\_", a value of -1 is returned.
    * 
    * The association between an attribute variable name and a generic attribute index can be specified at any time by calling [glBindAttribLocation][de.dasbabypixel.gamelauncher.gles.es20.glBindAttribLocation.glBindAttribLocation]. Attribute bindings do not go into effect until [glLinkProgram][de.dasbabypixel.gamelauncher.gles.es20.glLinkProgram.glLinkProgram] is called. After a program object has been linked successfully, the index values for attribute variables remain fixed until the next link command occurs. The attribute values can only be queried after a link if the link was successful. `glGetAttribLocation` returns the binding that actually went into effect the last time [glLinkProgram][de.dasbabypixel.gamelauncher.gles.es20.glLinkProgram.glLinkProgram] was called for the specified program object. Attribute bindings that have been specified since the last link operation are not returned by `glGetAttribLocation`.
    * 
    * Errors
    * ------
    * 
    * `GL_INVALID_OPERATION` is generated if _`program`_ is not a value generated by OpenGL.
    * 
    * `GL_INVALID_OPERATION` is generated if _`program`_ is not a program object.
    * 
    * `GL_INVALID_OPERATION` is generated if _`program`_ has not been successfully linked.
    * 
    * Associated Gets
    * ---------------
    * 
    * [glGetActiveAttrib][de.dasbabypixel.gamelauncher.gles.es20.glGetActiveAttrib.glGetActiveAttrib] with argument _`program`_ and the index of an active attribute
    * 
    * [glIsProgram][de.dasbabypixel.gamelauncher.gles.es20.glIsProgram.glIsProgram]
    * 
    * API Version Support
    * -------------------
    * 
    * 
    * |  | **OpenGL ES API Version** |  |  |  |
    * | --- | --- | --- | --- | --- |
    * | **Function Name** | **2.0** | **3.0** | **3.1** | **3.2** |
    * | `glGetAttribLocation` | ✔ | ✔ | ✔ | ✔ |
    * 
    * See Also
    * --------
    * 
    * [glBindAttribLocation][de.dasbabypixel.gamelauncher.gles.es20.glBindAttribLocation.glBindAttribLocation], [glIsProgram][de.dasbabypixel.gamelauncher.gles.es20.glIsProgram.glIsProgram], [glLinkProgram][de.dasbabypixel.gamelauncher.gles.es20.glLinkProgram.glLinkProgram], [glVertexAttrib][de.dasbabypixel.gamelauncher.gles.es20.glVertexAttrib1f.glVertexAttrib1f], [glVertexAttribPointer][de.dasbabypixel.gamelauncher.gles.es20.glVertexAttribPointer.glVertexAttribPointer]
    * 
    * Copyright
    * ---------
    * 
    * Copyright © 2003-2005 3Dlabs Inc. Ltd. This material may be distributed subject to the terms and conditions set forth in the Open Publication License, v 1.0, 8 June 1999. [https://opencontent.org/openpub/](https://opencontent.org/openpub/).
    * 
    * @see de.dasbabypixel.gamelauncher.gles.es20.glGetAttribLocation.glGetAttribLocation
    */
    fun glGetAttribLocation(program: UInt, name: String?): Int
}