package de.dasbabypixel.gamelauncher.gles.es20

interface glGetProgramInfoLog {
    /**
    * Name
    * ----
    * 
    * glGetProgramInfoLog — Returns the information log for a program object
    * 
    * C Specification
    * ---------------
    * 
    * | `void **glGetProgramInfoLog**(` | GLuint program, |
    * | --- | --- |
    * |   | GLsizei maxLength, |
    * |   | GLsizei \*length, |
    * |   | GLchar \*infoLog`)`; |
    * 
    * Parameters
    * ----------
    * 
    * _`program`_
    * 
    * Specifies the program object whose information log is to be queried.
    * 
    * _`maxLength`_
    * 
    * Specifies the size of the character buffer for storing the returned information log.
    * 
    * _`length`_
    * 
    * Returns the length of the string returned in _`infoLog`_ (excluding the null terminator).
    * 
    * _`infoLog`_
    * 
    * Specifies an array of characters that is used to return the information log.
    * 
    * Description
    * -----------
    * 
    * `glGetProgramInfoLog` returns the information log for the specified program object. The information log for a program object is modified when the program object is linked or validated. The string that is returned will be null terminated.
    * 
    * `glGetProgramInfoLog` returns in _`infoLog`_ as much of the information log as it can, up to a maximum of _`maxLength`_ characters. The number of characters actually returned, excluding the null termination character, is specified by _`length`_. If the length of the returned string is not required, a value of `NULL` can be passed in the _`length`_ argument. The size of the buffer required to store the returned information log can be obtained by calling [glGetProgramiv][de.dasbabypixel.gamelauncher.gles.es20.glGetProgramiv.glGetProgramiv] with the value `GL_INFO_LOG_LENGTH`.
    * 
    * The information log for a program object is either an empty string, or a string containing information about the last link operation, or a string containing information about the last validation operation. It may contain diagnostic messages, warning messages, and other information. When a program object is created, its information log will be a string of length 0.
    * 
    * Notes
    * -----
    * 
    * The information log for a program object is the OpenGL implementer's primary mechanism for conveying information about linking and validating. Therefore, the information log can be helpful to application developers during the development process, even when these operations are successful. Application developers should not expect different OpenGL implementations to produce identical information logs.
    * 
    * Errors
    * ------
    * 
    * `GL_INVALID_VALUE` is generated if _`program`_ is not a value generated by OpenGL.
    * 
    * `GL_INVALID_OPERATION` is generated if _`program`_ is not a program object.
    * 
    * `GL_INVALID_VALUE` is generated if _`maxLength`_ is less than 0.
    * 
    * Associated Gets
    * ---------------
    * 
    * [glGetProgramiv][de.dasbabypixel.gamelauncher.gles.es20.glGetProgramiv.glGetProgramiv] with argument `GL_INFO_LOG_LENGTH`
    * 
    * [glIsProgram][de.dasbabypixel.gamelauncher.gles.es20.glIsProgram.glIsProgram]
    * 
    * API Version Support
    * -------------------
    * 
    * 
    * |  | **OpenGL ES API Version** |  |  |  |
    * | --- | --- | --- | --- | --- |
    * | **Function Name** | **2.0** | **3.0** | **3.1** | **3.2** |
    * | glGetProgramInfoLog | ✔ | ✔ | ✔ | ✔ |
    * 
    * See Also
    * --------
    * 
    * [glCompileShader][de.dasbabypixel.gamelauncher.gles.es20.glCompileShader.glCompileShader], [glGetShaderInfoLog][de.dasbabypixel.gamelauncher.gles.es20.glGetShaderInfoLog.glGetShaderInfoLog], [glLinkProgram][de.dasbabypixel.gamelauncher.gles.es20.glLinkProgram.glLinkProgram], [glValidateProgram][de.dasbabypixel.gamelauncher.gles.es20.glValidateProgram.glValidateProgram]
    * 
    * Copyright
    * ---------
    * 
    * Copyright © 2003-2005 3Dlabs Inc. Ltd. Copyright © 2010-2015 Khronos Group. This material may be distributed subject to the terms and conditions set forth in the Open Publication License, v 1.0, 8 June 1999. [https://opencontent.org/openpub/](https://opencontent.org/openpub/).
    * 
    * @see de.dasbabypixel.gamelauncher.gles.es20.glGetProgramInfoLog.glGetProgramInfoLog
    */
    fun glGetProgramInfoLog(program: UInt, maxLength: UInt, length: java.nio.IntBuffer, infoLog: String)
}