package de.dasbabypixel.gamelauncher.gles.es20

interface glValidateProgram {
    /**
    * Name
    * ----
    * 
    * glValidateProgram — Validates a program object
    * 
    * C Specification
    * ---------------
    * 
    * | `void **glValidateProgram**(` | GLuint program`)`; |
    * | --- | --- |
    * 
    * Parameters
    * ----------
    * 
    * _`program`_
    * 
    * Specifies the handle of the program object to be validated.
    * 
    * Description
    * -----------
    * 
    * `glValidateProgram` checks to see whether the executables contained in _`program`_ can execute given the current OpenGL state. The information generated by the validation process will be stored in _`program`_'s information log. The validation information may consist of an empty string, or it may be a string containing information about how the current program object interacts with the rest of current OpenGL state. This provides a way for OpenGL implementers to convey more information about why the current program is inefficient, suboptimal, failing to execute, and so on.
    * 
    * The status of the validation operation will be stored as part of the program object's state. This value will be set to `GL_TRUE` if the validation succeeded, and `GL_FALSE` otherwise. It can be queried by calling [glGetProgramiv][de.dasbabypixel.gamelauncher.gles.es20.glGetProgramiv.glGetProgramiv] with arguments _`program`_ and `GL_VALIDATE_STATUS`. If validation is successful, _`program`_ is guaranteed to execute given the current state. Otherwise, _`program`_ is guaranteed to not execute.
    * 
    * This function is typically useful only during application development. The informational string stored in the information log is completely implementation dependent; therefore, an application should not expect different OpenGL implementations to produce identical information strings.
    * 
    * Notes
    * -----
    * 
    * This function mimics the validation operation that OpenGL implementations must perform when rendering commands are issued while programmable shaders are part of current state. The error `GL_INVALID_OPERATION` will be generated by any command that triggers the rendering of geometry if:
    * 
    * *   any two active samplers in the current program object are of different types, but refer to the same texture image unit,
    * 
    * *   the number of active samplers in the program exceeds the maximum number of texture image units allowed.
    * 
    * 
    * It may be difficult or cause a performance degradation for applications to catch these errors when rendering commands are issued. Therefore, applications are advised to make calls to `glValidateProgram` to detect these issues during application development.
    * 
    * Errors
    * ------
    * 
    * `GL_INVALID_VALUE` is generated if _`program`_ is not a value generated by OpenGL.
    * 
    * `GL_INVALID_OPERATION` is generated if _`program`_ is not a program object.
    * 
    * Associated Gets
    * ---------------
    * 
    * [glGetProgramiv][de.dasbabypixel.gamelauncher.gles.es20.glGetProgramiv.glGetProgramiv] with arguments _`program`_ and `GL_VALIDATE_STATUS`
    * 
    * [glGetProgramInfoLog][de.dasbabypixel.gamelauncher.gles.es20.glGetProgramInfoLog.glGetProgramInfoLog] with argument _`program`_
    * 
    * [glIsProgram][de.dasbabypixel.gamelauncher.gles.es20.glIsProgram.glIsProgram]
    * 
    * API Version Support
    * -------------------
    * 
    * 
    * |  | **OpenGL ES API Version** |  |  |  |
    * | --- | --- | --- | --- | --- |
    * | **Function Name** | **2.0** | **3.0** | **3.1** | **3.2** |
    * | glValidateProgram | ✔ | ✔ | ✔ | ✔ |
    * 
    * See Also
    * --------
    * 
    * [glLinkProgram][de.dasbabypixel.gamelauncher.gles.es20.glLinkProgram.glLinkProgram], [glUseProgram][de.dasbabypixel.gamelauncher.gles.es20.glUseProgram.glUseProgram]
    * 
    * Copyright
    * ---------
    * 
    * Copyright © 2003-2005 3Dlabs Inc. Ltd. Copyright © 2010-2015 Khronos Group. This material may be distributed subject to the terms and conditions set forth in the Open Publication License, v 1.0, 8 June 1999. [https://opencontent.org/openpub/](https://opencontent.org/openpub/).
    * 
    * @see de.dasbabypixel.gamelauncher.gles.es20.glValidateProgram.glValidateProgram
    */
    fun glValidateProgram(program: UInt)
}