[versions]
kotlin = "2.1.20"
buffers = "0.0.1"

[libraries]
buffers = { group = "io.github.dasbabypixel.gamelauncher.buffers", name = "buffers", version.ref = "buffers" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }