[versions]
htmlunit = "4.11.1"
jsoup = "1.21.1"

[libraries]
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
htmlunit = { group = "org.htmlunit", name = "htmlunit", version.ref = "htmlunit" }