package de.dasbabypixel.gamelauncher.gles.es32

interface glGetnUniformfv {
    /**
    * Name
    * ----
    * 
    * glGetUniform — Returns the value of a uniform variable
    * 
    * C Specification
    * ---------------
    * 
    * | `void **glGetUniformfv**(` | GLuint program, |
    * | --- | --- |
    * |   | GLint location, |
    * |   | GLfloat \*params`)`; |
    * 
    * | `void **glGetUniformiv**(` | GLuint program, |
    * | --- | --- |
    * |   | GLint location, |
    * |   | GLint \*params`)`; |
    * 
    * | `void **glGetUniformuiv**(` | GLuint program, |
    * | --- | --- |
    * |   | GLint location, |
    * |   | GLuint \*params`)`; |
    * 
    * | `void **glGetnUniformfv**(` | GLuint program, |
    * | --- | --- |
    * |   | GLint location, |
    * |   | GLsizei bufSize, |
    * |   | GLfloat \*params`)`; |
    * 
    * | `void **glGetnUniformiv**(` | GLuint program, |
    * | --- | --- |
    * |   | GLint location, |
    * |   | GLsizei bufSize, |
    * |   | GLint \*params`)`; |
    * 
    * | `void **glGetnUniformuiv**(` | GLuint program, |
    * | --- | --- |
    * |   | GLint location, |
    * |   | GLsizei bufSize, |
    * |   | GLuint \*params`)`; |
    * 
    * Parameters
    * ----------
    * 
    * _`program`_
    * 
    * Specifies the program object to be queried.
    * 
    * _`location`_
    * 
    * Specifies the location of the uniform variable to be queried.
    * 
    * _`bufSize`_
    * 
    * Specifies the size of the buffer _`params`_.
    * 
    * _`params`_
    * 
    * Returns the value of the specified uniform variable.
    * 
    * Description
    * -----------
    * 
    * `glGetUniform` and `glGetnUniform` return in _`params`_ the value(s) of the specified uniform variable. The type of the uniform variable specified by _`location`_ determines the number of values returned. If the uniform variable is defined in the shader as a boolean, int, unsigned int, or float, a single value will be returned. If it is defined as a vec2, ivec2, uvec2, or bvec2, two values will be returned. If it is defined as a vec3, ivec3, uvec3, or bvec3, three values will be returned, and so on. To query values stored in uniform variables declared as arrays, call `glGetUniform` for each element of the array. To query values stored in uniform variables declared as structures, call `glGetUniform` for each field in the structure. The values for uniform variables declared as a matrix will be returned in column major order.
    * 
    * The locations assigned to uniform variables are not known until the program object is linked. After linking has occurred, the command [glGetUniformLocation][de.dasbabypixel.gamelauncher.gles.es20.glGetUniformLocation.glGetUniformLocation] can be used to obtain the location of a uniform variable. This location value can then be passed to `glGetUniform` or `glGetnUniform` in order to query the current value of the uniform variable. After a program object has been linked successfully, the index values for uniform variables remain fixed until the next link command occurs. The uniform variable values can only be queried after a link if the link was successful.
    * 
    * The only difference between `glGetUniform` and `glGetnUniform` is that `glGetnUniform` will generate an error if size of the _`params`_ buffer, as described by _`bufSize`_, is not large enough to hold the result data.
    * 
    * Notes
    * -----
    * 
    * If an error is generated, no change is made to the contents of _`params`_.
    * 
    * Errors
    * ------
    * 
    * `GL_INVALID_VALUE` is generated if _`program`_ is not a value generated by OpenGL.
    * 
    * `GL_INVALID_OPERATION` is generated if _`program`_ is not a program object.
    * 
    * `GL_INVALID_OPERATION` is generated if _`program`_ has not been successfully linked.
    * 
    * `GL_INVALID_OPERATION` is generated if _`location`_ does not correspond to a valid uniform variable location for the specified program object.
    * 
    * `GL_INVALID_OPERATION` is generated by `glGetnUniform` if the buffer size required to store the requested data is greater than _`bufSize`_.
    * 
    * Associated Gets
    * ---------------
    * 
    * [glGetActiveUniform][de.dasbabypixel.gamelauncher.gles.es20.glGetActiveUniform.glGetActiveUniform] with arguments _`program`_ and the index of an active uniform variable
    * 
    * [glGetProgramiv][de.dasbabypixel.gamelauncher.gles.es20.glGetProgramiv.glGetProgramiv] with arguments _`program`_ and `GL_ACTIVE_UNIFORMS` or `GL_ACTIVE_UNIFORM_MAX_LENGTH`
    * 
    * [glGetUniformLocation][de.dasbabypixel.gamelauncher.gles.es20.glGetUniformLocation.glGetUniformLocation] with arguments _`program`_ and the name of a uniform variable
    * 
    * API Version Support
    * -------------------
    * 
    * 
    * |  | **OpenGL ES API Version** |  |  |  |
    * | --- | --- | --- | --- | --- |
    * | **Function Name** | **2.0** | **3.0** | **3.1** | **3.2** |
    * | `glGetUniformfv` | ✔ | ✔ | ✔ | ✔ |
    * | `glGetUniformiv` | ✔ | ✔ | ✔ | ✔ |
    * | `glGetUniformuiv` | \- | ✔ | ✔ | ✔ |
    * | `glGetnUniformfv` | \- | \- | \- | ✔ |
    * | `glGetnUniformiv` | \- | \- | \- | ✔ |
    * | `glGetnUniformuiv` | \- | \- | \- | ✔ |
    * 
    * See Also
    * --------
    * 
    * [glCreateProgram][de.dasbabypixel.gamelauncher.gles.es20.glCreateProgram.glCreateProgram], [glLinkProgram][de.dasbabypixel.gamelauncher.gles.es20.glLinkProgram.glLinkProgram], [glUniform][de.dasbabypixel.gamelauncher.gles.es20.glUniform1f.glUniform1f]
    * 
    * Copyright
    * ---------
    * 
    * Copyright © 2003-2005 3Dlabs Inc. Ltd. Copyright © 2010-2015 Khronos Group. This material may be distributed subject to the terms and conditions set forth in the Open Publication License, v 1.0, 8 June 1999. [https://opencontent.org/openpub/](https://opencontent.org/openpub/).
    * 
    * @see de.dasbabypixel.gamelauncher.gles.es20.glGetUniformfv.glGetUniformfv
    * @see de.dasbabypixel.gamelauncher.gles.es20.glGetUniformiv.glGetUniformiv
    * @see de.dasbabypixel.gamelauncher.gles.es30.glGetUniformuiv.glGetUniformuiv
    * @see de.dasbabypixel.gamelauncher.gles.es32.glGetnUniformfv.glGetnUniformfv
    * @see de.dasbabypixel.gamelauncher.gles.es32.glGetnUniformiv.glGetnUniformiv
    * @see de.dasbabypixel.gamelauncher.gles.es32.glGetnUniformuiv.glGetnUniformuiv
    */
    fun glGetnUniformfv(program: UInt, location: Int, bufSize: UInt, params: java.nio.FloatBuffer)
}