package de.dasbabypixel.gamelauncher.gles.es30

interface glGetStringi {
    /**
    * Name
    * ----
    * 
    * glGetString — return a string describing the current GL connection
    * 
    * C Specification
    * ---------------
    * 
    * | `const GLubyte* **glGetString**(` | GLenum name`)`; |
    * | --- | --- |
    * 
    * | `const GLubyte* **glGetStringi**(` | GLenum name, |
    * | --- | --- |
    * |   | GLuint index`)`; |
    * 
    * Parameters
    * ----------
    * 
    * _`name`_
    * 
    * Specifies a symbolic constant, one of `GL_EXTENSIONS`, `GL_RENDERER`, `GL_SHADING_LANGUAGE_VERSION`, `GL_VENDOR`, or `GL_VERSION`. `glGetStringi` accepts only the `GL_EXTENSIONS` token.
    * 
    * _`index`_
    * 
    * For `glGetStringi`, specifies the index of the string to return.
    * 
    * Description
    * -----------
    * 
    * `glGetString` returns a pointer to a static string describing some aspect of the current GL connection. _`name`_ can be one of the following:
    * 
    * `GL_EXTENSIONS`
    * 
    * Returns the extension string supported by the implementation.
    * 
    * `GL_VENDOR`
    * 
    * Returns the company responsible for this GL implementation. This name does not change from release to release.
    * 
    * `GL_RENDERER`
    * 
    * Returns the name of the renderer. This name is typically specific to a particular configuration of a hardware platform. It does not change from release to release.
    * 
    * `GL_VERSION`
    * 
    * Returns a version or release number.
    * 
    * `GL_SHADING_LANGUAGE_VERSION`
    * 
    * Returns a version or release number for the shading language.
    * 
    * `glGetStringi` returns a pointer to a static string indexed by _`index`_. _`name`_ can be one of the following:
    * 
    * `GL_EXTENSIONS`
    * 
    * Returns the extension string supported by the implementation at _`index`_.
    * 
    * Strings `GL_VENDOR` and `GL_RENDERER` together uniquely specify a platform. They do not change from release to release and should be used by platform-recognition algorithms.
    * 
    * The `GL_VERSION` and `GL_SHADING_LANGUAGE_VERSION` strings begin with a version number. The version number uses one of these forms:
    * 
    * _major\_number.minor\_number_ _major\_number.minor\_number.release\_number_
    * 
    * Vendor-specific information may follow the version number. Its format depends on the implementation, but a space always separates the version number and the vendor-specific information.
    * 
    * All strings are null-terminated.
    * 
    * Notes
    * -----
    * 
    * If an error is generated, `glGetString` returns 0.
    * 
    * The client and server may support different versions. `glGetString` always returns a compatible version number. The release number always describes the server.
    * 
    * There is no defined relationship between the order in which extension names appear in the non-indexed string and the order in which they appear in the indexed query.
    * 
    * There is no defined relationship between any particular extension name and the index values; an extension name may correspond to a different index in different GL contexts and/or implementations.
    * 
    * Errors
    * ------
    * 
    * `GL_INVALID_ENUM` is generated if _`name`_ is not an accepted value.
    * 
    * `GL_INVALID_VALUE` is generated by `glGetStringi` if _`index`_ is outside the valid range for indexed state _`name`_.
    * 
    * API Version Support
    * -------------------
    * 
    * 
    * |  | **OpenGL ES API Version** |  |  |  |
    * | --- | --- | --- | --- | --- |
    * | **Function Name** | **2.0** | **3.0** | **3.1** | **3.2** |
    * | `GetString` | ✔ | ✔ | ✔ | ✔ |
    * | `GetStringi` | \- | ✔ | ✔ | ✔ |
    * 
    * Copyright
    * ---------
    * 
    * Copyright © 1991-2006 Silicon Graphics, Inc. Copyright © 2010-2015 Khronos Group. This document is licensed under the SGI Free Software B License. For details, see [https://khronos.org/registry/OpenGL-Refpages/LICENSES/LicenseRef-FreeB.txt](https://khronos.org/registry/OpenGL-Refpages/LICENSES/LicenseRef-FreeB.txt).
    * 
    * @see de.dasbabypixel.gamelauncher.gles.es20.glGetString.glGetString
    * @see de.dasbabypixel.gamelauncher.gles.es30.glGetStringi.glGetStringi
    */
    fun glGetStringi(name: Int, index: UInt): String
}