package de.dasbabypixel.gamelauncher.gles.es30

interface glTransformFeedbackVaryings {
    /**
    * Name
    * ----
    * 
    * glTransformFeedbackVaryings — specify values to record in transform feedback buffers
    * 
    * C Specification
    * ---------------
    * 
    * | `void **glTransformFeedbackVaryings**(` | GLuint program, |
    * | --- | --- |
    * |   | GLsizei count, |
    * |   | const char \*\* varyings, |
    * |   | GLenum bufferMode`)`; |
    * 
    * Parameters
    * ----------
    * 
    * _`program`_
    * 
    * The name of the target program object.
    * 
    * _`count`_
    * 
    * The number of varying variables used for transform feedback.
    * 
    * _`varyings`_
    * 
    * An array of _`count`_ zero-terminated strings specifying the names of the varying variables to use for transform feedback.
    * 
    * _`bufferMode`_
    * 
    * Identifies the mode used to capture the varying variables when transform feedback is active. _`bufferMode`_ must be `GL_INTERLEAVED_ATTRIBS` or `GL_SEPARATE_ATTRIBS`.
    * 
    * Description
    * -----------
    * 
    * The names of the vertex or geometry shader outputs to be recorded in transform feedback mode are specified using `glTransformFeedbackVaryings`. When a geometry shader is active, transform feedback records the values of selected geometry shader output variables from the emitted vertices. Otherwise, the values of the selected vertex shader outputs are recorded.
    * 
    * The state set by `glTranformFeedbackVaryings` is stored and takes effect next time [glLinkProgram][de.dasbabypixel.gamelauncher.gles.es20.glLinkProgram.glLinkProgram] is called on _`program`_. When [glLinkProgram][de.dasbabypixel.gamelauncher.gles.es20.glLinkProgram.glLinkProgram] is called, _`program`_ is linked so that the values of the specified varying variables for the vertices of each primitive generated by the GL are written to a single buffer object if _`bufferMode`_ is `GL_INTERLEAVED_ATTRIBS` or multiple buffer objects if _`bufferMode`_ is `GL_SEPARATE_ATTRIBS`.
    * 
    * In addition to the errors generated by `glTransformFeedbackVaryings`, the program _`program`_ will fail to link if:
    * 
    * *   The count specified by `glTransformFeedbackVaryings` is non-zero, but the program object has no vertex, tesselation evaluation, or geometry shader.
    * 
    * *   Any variable name specified in the _`varyings`_ array is not declared as a built-in or user-defined output in the shader stage whose outputs can be recorded.
    * 
    * *   Any two entries in the _`varyings`_ array specify the same varying variable.
    * 
    * *   The total number of components to capture in any varying variable in _`varyings`_ is greater than the constant `GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS` and the buffer mode is `GL_SEPARATE_ATTRIBS`.
    * 
    * *   The total number of components to capture is greater than the constant `GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS` and the buffer mode is `GL_INTERLEAVED_ATTRIBS`.
    * 
    * 
    * Errors
    * ------
    * 
    * `GL_INVALID_VALUE` is generated if _`program`_ is not the name of a program object.
    * 
    * `GL_INVALID_VALUE` is generated if _`bufferMode`_ is `GL_SEPARATE_ATTRIBS` and _`count`_ is greater than the implementation-dependent limit `GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS`.
    * 
    * Associated Gets
    * ---------------
    * 
    * [glGetTransformFeedbackVarying][de.dasbabypixel.gamelauncher.gles.es30.glGetTransformFeedbackVarying.glGetTransformFeedbackVarying]
    * 
    * API Version Support
    * -------------------
    * 
    * 
    * |  | **OpenGL ES API Version** |  |  |  |
    * | --- | --- | --- | --- | --- |
    * | **Function Name** | **2.0** | **3.0** | **3.1** | **3.2** |
    * | glTransformFeedbackVaryings | \- | ✔ | ✔ | ✔ |
    * 
    * See Also
    * --------
    * 
    * [glBeginTransformFeedback][de.dasbabypixel.gamelauncher.gles.es30.glBeginTransformFeedback.glBeginTransformFeedback], [glEndTransformFeedback][de.dasbabypixel.gamelauncher.gles.es30.glBeginTransformFeedback.glBeginTransformFeedback], [glGetTransformFeedbackVarying][de.dasbabypixel.gamelauncher.gles.es30.glGetTransformFeedbackVarying.glGetTransformFeedbackVarying]
    * 
    * Copyright
    * ---------
    * 
    * Copyright © 2010-2015 Khronos Group. This material may be distributed subject to the terms and conditions set forth in the Open Publication License, v 1.0, 8 June 1999. [https://opencontent.org/openpub/](https://opencontent.org/openpub/).
    * 
    * @see de.dasbabypixel.gamelauncher.gles.es30.glTransformFeedbackVaryings.glTransformFeedbackVaryings
    */
    fun glTransformFeedbackVaryings(program: UInt, count: UInt, varyings: de.dasbabypixel.gamelauncher.buffers.PointerBuffer, bufferMode: Int)
}