package de.dasbabypixel.gamelauncher.gles.es30

interface glUniformBlockBinding {
    /**
    * Name
    * ----
    * 
    * glUniformBlockBinding — assign a binding point to an active uniform block
    * 
    * C Specification
    * ---------------
    * 
    * | `void **glUniformBlockBinding**(` | GLuint program, |
    * | --- | --- |
    * |   | GLuint uniformBlockIndex, |
    * |   | GLuint uniformBlockBinding`)`; |
    * 
    * Parameters
    * ----------
    * 
    * _`program`_
    * 
    * The name of a program object containing the active uniform block whose binding to assign.
    * 
    * _`uniformBlockIndex`_
    * 
    * The index of the active uniform block within _`program`_ whose binding to assign.
    * 
    * _`uniformBlockBinding`_
    * 
    * Specifies the binding point to which to bind the uniform block with index _`uniformBlockIndex`_ within _`program`_.
    * 
    * Description
    * -----------
    * 
    * Binding points for active uniform blocks are assigned using `glUniformBlockBinding`. Each of a program's active uniform blocks has a corresponding uniform buffer binding point. _`program`_ is the name of a program object for which the command [glLinkProgram][de.dasbabypixel.gamelauncher.gles.es20.glLinkProgram.glLinkProgram] has been issued in the past.
    * 
    * If successful, `glUniformBlockBinding` specifies that _`program`_ will use the data store of the buffer object bound to the binding point _`uniformBlockBinding`_ to extract the values of the uniforms in the uniform block identified by _`uniformBlockIndex`_.
    * 
    * When a program object is linked or re-linked, the uniform buffer object binding point assigned to each of its active uniform blocks is reset to zero.
    * 
    * Errors
    * ------
    * 
    * `GL_INVALID_VALUE` is generated if _`uniformBlockIndex`_ is not an active uniform block index of _`program`_.
    * 
    * `GL_INVALID_VALUE` is generated if _`uniformBlockBinding`_ is greater than or equal to the value of `GL_MAX_UNIFORM_BUFFER_BINDINGS`.
    * 
    * `GL_INVALID_VALUE` is generated if _`program`_ is not the name of a program object generated by the GL.
    * 
    * Associated Gets
    * ---------------
    * 
    * [glGet][de.dasbabypixel.gamelauncher.gles.es20.glGetBooleanv.glGetBooleanv] with argument `GL_MAX_UNIFORM_BUFFER_BINDINGS`
    * 
    * [glGetActiveUniformBlockiv][de.dasbabypixel.gamelauncher.gles.es30.glGetActiveUniformBlockiv.glGetActiveUniformBlockiv] with argument `GL_UNIFORM_BLOCK_BINDING`
    * 
    * API Version Support
    * -------------------
    * 
    * 
    * |  | **OpenGL ES API Version** |  |  |  |
    * | --- | --- | --- | --- | --- |
    * | **Function Name** | **2.0** | **3.0** | **3.1** | **3.2** |
    * | glUniformBlockBinding | \- | ✔ | ✔ | ✔ |
    * 
    * See Also
    * --------
    * 
    * [glLinkProgram][de.dasbabypixel.gamelauncher.gles.es20.glLinkProgram.glLinkProgram], [glBindBufferBase][de.dasbabypixel.gamelauncher.gles.es30.glBindBufferBase.glBindBufferBase], [glBindBufferRange][de.dasbabypixel.gamelauncher.gles.es30.glBindBufferRange.glBindBufferRange], [glGetActiveUniformBlockiv][de.dasbabypixel.gamelauncher.gles.es30.glGetActiveUniformBlockiv.glGetActiveUniformBlockiv]
    * 
    * Copyright
    * ---------
    * 
    * Copyright © 2010-2015 Khronos Group. This material may be distributed subject to the terms and conditions set forth in the Open Publication License, v 1.0, 8 June 1999. [https://opencontent.org/openpub/](https://opencontent.org/openpub/).
    * 
    * @see de.dasbabypixel.gamelauncher.gles.es30.glUniformBlockBinding.glUniformBlockBinding
    */
    fun glUniformBlockBinding(program: UInt, uniformBlockIndex: UInt, uniformBlockBinding: UInt)
}