name: Publish

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build and Publish
        run: ./gradlew -PSonatypeUsername="${{ secrets.SONATYPE_USERNAME }}" -PSonatypePassword="${{ secrets.SONATYPE_PASSWORD }}" publishToSonatype closeAndReleaseSonatypeStagingRepository

on: [ workflow_dispatch ]